/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_zkp_com_myapplication_PngUtils */

#ifndef _Included_com_zkp_com_myapplication_PngUtils
#define _Included_com_zkp_com_myapplication_PngUtils

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_zkp_com_myapplication_PngUtils
 * Method:    checkIsPng
 * Signature: (Landroid/content/res/AssetManager;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL
Java_com_zkp_com_myapplication_PngUtils_checkIsPng(JNIEnv *, jclass, jstring);

JNIEXPORT jstring JNICALL
Java_com_zkp_com_myapplication_PngUtils_readPngHighLevel(JNIEnv *, jclass, jstring);

JNIEXPORT jstring JNICALL
Java_com_zkp_com_myapplication_PngUtils_lowLevelReadLowLevelWrite(JNIEnv *, jclass,
                                                                jstring, jstring);

JNIEXPORT jstring JNICALL
        Java_com_zkp_com_myapplication_PngUtils_highLevelReadHighLevelWrite(JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
